// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyShopSite.Data;

namespace MyShopSite.Migrations
{
    [DbContext(typeof(MyShopSiteContext))]
    [Migration("20210407144114_seedata")]
    partial class seedata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyShopSite.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "تجهیزات خانگی",
                            Name = "لوازم برقی"
                        },
                        new
                        {
                            Id = 2,
                            Description = " همراه با تخفیف ویژه",
                            Name = "خوراکی ها"
                        },
                        new
                        {
                            Id = 3,
                            Description = "تنوع پوشاک مردانه و زنانه",
                            Name = "پوشاک"
                        },
                        new
                        {
                            Id = 4,
                            Description = "شامل بدلیجات،نقره و طلا",
                            Name = " زیورآلات"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
